### ISSUE TITLE
error with function decode-msdos-timestamp

### ISSUE THREAD

**Issue by Moriaty0o0** [Shinmera/zippy#12]
when I use zippy to extract zip file in LispWorks 8.1 Hobbyist DV, LispWorks show an error: 
```
Error: ENCODE-UNIVERSAL-TIME: timezone NIL must be a rational multiple of 1/3600 in the range -24 to 24
```
But if I use sbcl , everything is ok, and when i deleted the last argument nil in function encode-universal-time, LispWorks also works. So I ask help for Lispworks, he told me that  ANSI spec says the last argument is a time zone ,Deleting the last argument nil is a good option because there is no need to pass it like that in SBCL either.

So is it better to delete the last argument nil ?

**Comment by Shinmera** [comment]
No, leaving the argument out defaults to the local TZ, which is wrong. The correct argument is 0.
