### ISSUE TITLE
can not extract this file 

### ISSUE THREAD

**Issue by tengelyeah** [Shinmera/zippy#7]
Invalid index 4096 for (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (4096)), should be a non-negative integer below 4096.
   [Condition of type SB-INT:INVALID-ARRAY-INDEX-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {10038CD1E3}>)

Backtrace:
  0: (3BZ::DECOMPRESS-DEFLATE/VECTOR #<3BZ::OCTET-VECTOR-CONTEXT {10054D8DF3}> #S(ORG.SHIRAKUMO.ZIPPY::DEFLATE-STATE :CURRENT-STATE :DECODE-COMPRESSED-DATA :LAST-BLOCK-FLAG NIL :DYNAMIC-HUFFMAN-TREE #1=(#S..
  1: ((:METHOD ORG.SHIRAKUMO.ZIPPY:CALL-WITH-DECOMPRESSED-BUFFER (T T T T 3BZ::DEFLATE-STATE)) #<FUNCTION (FLET ORG.SHIRAKUMO.ZIPPY:OUTPUT :IN ORG.SHIRAKUMO.ZIPPY:ENTRY-TO-FILE) {100554862B}> #(74 243 249 ..
  2: ((FLET ORG.SHIRAKUMO.ZIPPY:OUTPUT :IN ORG.SHIRAKUMO.ZIPPY:CALL-WITH-DECRYPTED-BUFFER) 0 4096)
  3: ((:METHOD ORG.SHIRAKUMO.ZIPPY:CALL-WITH-DECRYPTED-BUFFER (T STREAM T ORG.SHIRAKUMO.ZIPPY::STREAM-DECRYPTION-STATE)) #<FUNCTION (FLET ORG.SHIRAKUMO.ZIPPY::DECOMPRESS :IN ORG.SHIRAKUMO.ZIPPY:DECODE-ENTR..
  4: (ORG.SHIRAKUMO.ZIPPY:ENTRY-TO-FILE #P"/tmp/OEBPS/Images/image00731.jpeg" #<ORG.SHIRAKUMO.ZIPPY:ZIP-ENTRY "OEBPS/Images/image00731.jpeg"> :IF-EXISTS :ERROR :PASSWORD NIL :RESTORE-ATTRIBUTES T)
  5: (ORG.SHIRAKUMO.ZIPPY:EXTRACT-ZIP #<ORG.SHIRAKUMO.ZIPPY:ZIP-FILE #P"/tmp/pingfan.zip"> "/tmp/pingfan" :IF-EXISTS :ERROR :PASSWORD NIL)
  6: (ORG.SHIRAKUMO.ZIPPY::CALL-WITH-INPUT-ZIP-FILE #<FUNCTION (LAMBDA (ORG.SHIRAKUMO.ZIPPY::ZIP) :IN ORG.SHIRAKUMO.ZIPPY:EXTRACT-ZIP) {1004FDA71B}> "/tmp/pingfan.zip" :START 0 :END NIL)
  7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ORG.SHIRAKUMO.ZIPPY:EXTRACT-ZIP "/tmp/pingfan.zip" "/tmp/pingfan") #<NULL-LEXENV>)
  8: (EVAL (ORG.SHIRAKUMO.ZIPPY:EXTRACT-ZIP "/tmp/pingfan.zip" "/tmp/pingfan"))
 --more--
[pingfan.zip](https://github.com/Shinmera/zippy/files/11449847/pingfan.zip)

**Comment by fisxoj** [comment]
I just noticed this while cleaning up something I did that hit this. I believe this is also caused by https://github.com/3b/3bz/pull/17 which was just fixed and seems to be updated in the latest quicklisp, since my use case started working.  Hope that's helpful.
